plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

// Itt adjuk meg a letöltési forrásokat
repositories {
    maven {
        url = uri("https://maven.terraformersmc.com/releases/")
        metadataSources {
            mavenPom()
        }
    } // ModMenu helye
    maven {
        url = uri("https://maven.fabricmc.net/")
        metadataSources {
            artifact()
            mavenPom()
        }
    } // Fabric API helye
    mavenCentral() // Általános Java könyvtárak
}

loom {
	// KIVÉVE: splitEnvironmentSourceSets() - Így sokkal stabilabb Termuxon!
	mods {
		"optimobileplusz" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:intermediary:${project.mappings_version}"

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // Mod Menu integráció
    modImplementation "com.terraformersmc:modmenu:11.0.1"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(25)
    targetCompatibility = JavaVersion.toVersion(25)
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}
