name: publish
on:
  release:
    types: [published] # Csak akkor indul el, ha a GitHubon rámész a "Create a new release" gombra és közzéteszed

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
        
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
        
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
          
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build

      - name: Publish to CurseForge
        uses: AykutSarac/actions-curseforge@v1
        with:
          # A GitHub Secrets tokened
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          # A modod CurseForge azonosítója
          project_id: 1542509
          
          # Kiválasztja a kész mod fájlt, kizárva a sources-t
          file_path: build/libs/!(*-sources).jar
          
          # A CurseForge felületén megjelenő verziónév (opcionális, a GitHub tag nevét kapja meg)
          file_name: OptiElitePlusz-${{ github.ref_name }}.jar
          
          # Támogatott verzió, loader és kiadási típus
          game_versions: '1.21.1'
          loaders: 'fabric'
          
          # Mivel most bétát adsz ki, a GitHub Release-ből ezt automatikusan kiolvassa!
          # Ha a GitHubon bepipálod a "Set as a pre-release" gombot, beta lesz, ha nem, akkor release.
          release_type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
          
          # Átveszi a GitHub Release leírását changelognak
          changelog: ${{ github.event.release.body }}
          
